# Use root/example as user/password credentials
version: '3.1'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./tmp:/tmp_data
      - ~/.aws/:/root/.aws:ro
    working_dir: /app
    restart: always
    depends_on:
      - tika    
    environment:
      NODE_ENV: development
      GOOGLE_APPLICATION_CREDENTIALS: /app/GOOGLE_APPLICATION_CREDENTIALS.json
    ports:
      - 3000:3000
    command: npm run dev    
  tika:
    image: logicalspark/docker-tikaserver
    restart: always
    expose:
      - 9998    